micronaut:
  application:
    name: wst
datasources:
  default:
    url: ${DB_URL:`jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}
    driverClassName: ${DB_DRIVER:`org.h2.Driver`}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:''}
    schema-generate: ${DB_SCHEMA_GENERATE:CREATE_DROP}
    dialect: ${DB_DIALECT:H2}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: ${DB_AUTO_DDL:update}
        show_sql: ${DB_SHOW_SQL:true}
        format_sql: ${DB_FORMAT_SQL:true}

grpc:
  server:
    port: ${GRPC_PORT:50049}
    keep-alive-time: 3h
    max-inbound-message-size: 1024
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    wstRoute:
      address: ${WST_ROUTE_CHANNEL:`localhost:50050`}
      plaintext: true
      max-retry-attempts: 10

kafka:
  bootstrap:
    servers: ${KAFKA_HOST:`localhost:9092`}

siscomex:
  ncm:
    url: 'https://portalunico.siscomex.gov.br/classif/api/nomenclatura/pesquisa/'
